# Generated by Django 2.2.17 on 2020-12-06 11:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import organization.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('company_mobile', models.CharField(error_messages={'unique': 'A Company with that mobile already exists.'}, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0][1-9]\\d{9}$|^[6-9]\\d{9}$')], verbose_name='Company Mobile Number')),
                ('company_website_url', models.URLField(blank=True, unique=True, verbose_name='Company Website URL')),
                ('company_address', models.TextField(verbose_name='Company Address')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/', verbose_name='Company Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Company Active?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('employee_id', models.CharField(error_messages={'unique': 'An Employee with that ID already exists.'}, max_length=255, unique=True, verbose_name='Employee ID')),
                ('name', models.CharField(max_length=255, verbose_name='Employee Full Name')),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'An Employee with that mobile already exists.'}, max_length=254, unique=True, verbose_name='Employee Email')),
                ('mobile', models.CharField(blank=True, error_messages={'unique': 'An Employee with that mobile already exists.'}, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0][1-9]\\d{9}$|^[6-9]\\d{9}$')], verbose_name='Employee Mobile Number')),
                ('designation', models.CharField(max_length=255, verbose_name='Employee Designation')),
                ('department', models.CharField(max_length=255, verbose_name='Employee Department')),
                ('joining_date', models.DateField(blank=True, verbose_name='Employee Joining Date')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Employee Bank Name')),
                ('account_holder_name', models.CharField(blank=True, max_length=255, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(blank=True, max_length=255, verbose_name='Account Number')),
                ('account_type', models.CharField(blank=True, max_length=50, verbose_name='Account Type')),
                ('upi_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='UPI ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Employee Active?')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.Company')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slip_number', models.CharField(default=organization.utils.generate_slip_id, max_length=12, verbose_name='Salary Slip ID')),
                ('salary_slip_date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('basic', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Basic & DA')),
                ('house_rent_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='House Rent Allowance')),
                ('misc_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Miscellaneous Allowance')),
                ('joining_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Joining Bonus')),
                ('conveyance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Conveyance')),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Gross Earnings')),
                ('provident_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Provident Fund')),
                ('tds_it', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='TDS/IT')),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Professional Tax')),
                ('gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='GST')),
                ('gross_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Gross Deductions')),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Net Pay')),
                ('reference_number', models.CharField(blank=True, max_length=255, verbose_name='Transaction ID')),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('CHEQUE', 'CHEQUE'), ('NEFT', 'NEFT'), ('IMPS', 'IMPS')], default='IMPS', max_length=10, verbose_name='Payment Method')),
                ('payment_transfer_date', models.DateField(auto_now_add=True, verbose_name='Payment Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.Employee')),
            ],
            options={
                'verbose_name': 'Salary Slip',
                'verbose_name_plural': 'Salary Slips',
            },
        ),
    ]
